src/Entity/Profesion.php
<?php

namespace App\Entity;

use App\Repository\ProfesionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfesionRepository::class)
 */
class Profesion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nombre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="profesiones")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(?string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Posts;
use App\Entity\Comentarios;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    /**
     * @Route("/", name="dashboard")
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $user = $this->getUser();
       
        if($user){
            $em= $this->getDoctrine()->getManager();
            $comentarios = $em->getRepository(Comentarios::class)->BuscarComentarios($user->getId());           
            $query = $em->getRepository(Posts::class)->findAllPosts();
            $pagination = $paginator->paginate(
                $query, /* query NOT result */
                $request->query->getInt('page', 1), /*page number*/
                2 /*limit per page*/
            );
            return $this->render('dashboard/index.html.twig', [
                'pagination' => $pagination,
                'comentarios'=>$comentarios
            ]);

        }else{
            return $this->RedirectToRoute('app_login');
        }
        
        //El entity manager es el encargado de la gestión de BD
       
    }
}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} - Dashboard{% endblock %}

{% block body %}
    {{parent()}}
    <div class="container mt-4"> 
    <div class="container">
        <div class="row">
            <div class="col-md-8 cursor">
            {% for post in pagination %}
                <div class="bg-white rounded p-3 my-3"  onclick="window.location.href='{{path('verPost',{id:post.id})}}'">
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">
                            <h3>{{post.titulo}}</h3>
                            <div class="my-3 bg-yellow"> <i class="fa fa-user"></i><strong> Creado por {{post.nombre}}</strong></div>
                            <div class=" bg-green"><i class="far fa-clock"></i> <strong>Fecha de publicación: {{post.fecha_publicacion | date}}</strong></div>
                        </div>
                        <div class="p-2 bd-highlight">
                            <div class="align-self-center">
                                <img class="rounded" src={{asset ('uploads/photos/'~post.foto)}} width="150px">
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="bg-white rounded p-3 my-3">
                    <h4>Comentarios</h4>
                      {% for comentario in comentarios %}
                        <div class="bg-white my-2">
                            <a href="{{ path('verPost',{id:comentario.id}) }}">{{ comentario.titulo }}</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    

<div class="d-flex justify-content-center">
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</div>
{% endblock %}